ToDoApplication.Web/Controllers/TaskStatusController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoApplication.Application.DTOs;
using ToDoApplication.Application.Interfaces;

namespace ToDoApplication.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TaskStatusController : Controller
    {
        private readonly ITaskStatusesService statusService;
        private readonly IToDoTaskService taskService;
        private readonly IValidator<TaskStatusesDto> validator;

        public TaskStatusController(
            ITaskStatusesService statusService,
            IToDoTaskService taskService,
            IValidator<TaskStatusesDto> validator)
        {
            this.statusService = statusService;
            this.taskService = taskService;
            this.validator = validator;
        }

        public IActionResult Index()
        {
            var taskStatuses = this.statusService.GetAll();

            return this.View(taskStatuses);
        }

        [Route("TaskStatuses/Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            var taskStatus = await this.statusService.GetByIdAsync(id);
            taskStatus.Tasks = this.taskService.GetAll().Where(x => x.StatusId == id);

            return this.View(taskStatus);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View(new TaskStatusesDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(TaskStatusesDto status)
        {
            var result = await this.validator.ValidateAsync(status);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Add", status);
            }

            var statusId = await this.statusService.AddAsync(status);

            return this.RedirectToAction("Details", new { id = statusId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var taskStatus = await this.statusService.GetByIdAsync(id);

            return this.View(taskStatus);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TaskStatusesDto status)
        {
            var result = await this.validator.ValidateAsync(status);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Edit", status);
            }

            var statusId = await this.statusService.UpdateAsync(status.Id, status);

            return this.RedirectToAction("Details", new { id = statusId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.statusService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

ToDoApplication.Web/Controllers/ToDoListController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoApplication.Application.DTOs;
using ToDoApplication.Application.Interfaces;
using ToDoApplication.Domain.Models;
using ToDoApplication.Web.Models;
using ToDoApplication.Web.Models.ViewModels;

namespace ToDoApplication.Web.Controllers
{
    [Authorize]
    public class ToDoListController : Controller
    {
        private readonly IToDoListService toDoListService;
        private readonly IToDoTaskService toDoTaskService;
        private readonly IValidator<ToDoListDto> validator;
        private readonly UserManager<ApplicationUser> userManager;

        public ToDoListController(
            IToDoListService toDoListService,
            IToDoTaskService toDoTaskService,
            IValidator<ToDoListDto> validator,
            UserManager<ApplicationUser> userManager)
        {
            this.toDoListService = toDoListService;
            this.toDoTaskService = toDoTaskService;
            this.validator = validator;
            this.userManager = userManager;
        }

        [Route("ToDoList/{showAll?}")]
        public IActionResult Index(bool showAll)
        {
            var lists = new ToDoListsVM();
            var userId = this.userManager.GetUserId(this.HttpContext.User);

            lists.ShowAll = showAll;

            lists.ToDoLists = this.toDoListService.GetAll().Where(x => x.UserId == userId);
            CountDefaultListItems.FillNumberOfTasks(userId, lists, this.toDoListService);

            if (!showAll)
            {
                lists.ToDoLists = lists.ToDoLists.Where(x => !x.IsHidden);
            }

            return this.View(lists);
        }

        [Route("ToDoList/Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            var toDoTasks = this.toDoTaskService.GetAll(id);
            var user = await this.userManager.GetUserAsync(this.HttpContext.User);
            var toDoList = await this.toDoListService.GetByIdAsync(id);

            toDoList.Tasks = toDoTasks;
            toDoList.User = user;

            return this.View(toDoList);
        }

        [HttpGet]
        [Route("ToDoList/Add")]
        public IActionResult Add()
        {
            return this.View(new ToDoListDto());
        }

        [Route("ToDoList/Add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(ToDoListDto toDoList)
        {
            toDoList.CreationDate = DateTimeOffset.Now;

            var result = await this.validator.ValidateAsync(toDoList);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Add", toDoList);
            }

            string userId = this.userManager.GetUserId(this.HttpContext.User);

            toDoList.User = null!;
            toDoList.UserId = userId;

            var toDoListId = await this.toDoListService.AddAsync(toDoList);

            return this.RedirectToAction("Details", new { id = toDoListId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var toDoList = await this.toDoListService.GetByIdAsync(id);

            return this.View(toDoList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ToDoListDto toDoList)
        {
            var result = await this.validator.ValidateAsync(toDoList);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Edit", toDoList);
            }

            var toDoListId = await this.toDoListService.UpdateAsync(toDoList.Id, toDoList);

            return this.RedirectToAction("Details", new { id = toDoListId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.toDoListService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }

        [Route("ToDoList/Copy/{listId:int}")]
        public async Task<IActionResult> Copy(int listId)
        {
            await this.toDoListService.CopyAsync(listId);

            return this.RedirectToAction("Index");
        }
    }
}

ToDoApplication.Web/Controllers/ToDoTaskController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoApplication.Application.DTOs;
using ToDoApplication.Application.Interfaces;
using ToDoApplication.Domain.Models;
using ToDoApplication.Web.Models;
using ToDoApplication.Web.Models.ViewModels;

namespace ToDoApplication.Web.Controllers
{
    [Authorize]
    public class ToDoTaskController : Controller
    {
        private readonly IToDoTaskService toDoTaskService;
        private readonly ITaskStatusesService statusService;
        private readonly ITaskCategoryService categoryService;
        private readonly ITaskPriorityService priorityService;
        private readonly IToDoListService toDoListService;
        private readonly ITaskNotesService taskNotesService;
        private readonly IValidator<ToDoTaskDto> validator;
        private readonly UserManager<ApplicationUser> userManager;

        public ToDoTaskController(
            IToDoTaskService toDoTaskService,
            ITaskStatusesService statusService,
            ITaskCategoryService categoryService,
            ITaskPriorityService priorityService,
            IToDoListService toDoListService,
            ITaskNotesService taskNotesService,
            IValidator<ToDoTaskDto> validator,
            UserManager<ApplicationUser> userManager)
        {
            this.toDoTaskService = toDoTaskService;
            this.statusService = statusService;
            this.categoryService = categoryService;
            this.priorityService = priorityService;
            this.toDoListService = toDoListService;
            this.taskNotesService = taskNotesService;
            this.validator = validator;
            this.userManager = userManager;
        }

        [Route("ToDoList/{listId:int}/Tasks/{hide?}")]
        public async Task<IActionResult> Index(int listId, bool showAll)
        {
            var list = await this.toDoListService.GetByIdAsync(listId);
            var userId = this.userManager.GetUserId(this.HttpContext.User);

            var listWithTasks = new ToDoListWithTasksVM();

            listWithTasks = list.Name switch
            {
                "Important" => new ToDoListWithTasksVM
                {
                    ListId = listId,
                    ShowAll = showAll,
                    ToDoTasks = this.toDoListService.GetAllUserImportantTasks(userId)
                },
                "Daily" => new ToDoListWithTasksVM
                {
                    ListId = listId,
                    ShowAll = showAll,
                    ToDoTasks = this.toDoListService.GetAllUserDailyTasks(userId)
                },
                "Today" => new ToDoListWithTasksVM
                {
                    ListId = listId,
                    ShowAll = showAll,
                    ToDoTasks = this.toDoListService.GetAllUserTodaysTasks(userId)
                },
                _ => new ToDoListWithTasksVM
                {
                    ListId = listId,
                    ShowAll = showAll,
                    ToDoTasks = this.toDoTaskService.GetAll(listId)
                },
            };
            if (!showAll)
            {
                listWithTasks.ToDoTasks = listWithTasks.ToDoTasks.Where(x => !x.IsCompleted);
            }

            foreach (var task in listWithTasks.ToDoTasks)
            {
                task.List = await this.toDoListService.GetByIdAsync(task.ListId);
                task.Category = await this.categoryService.GetByIdAsync(task.CategoryId);
                task.Status = await this.statusService.GetByIdAsync(task.StatusId);
                task.Priority = await this.priorityService.GetByIdAsync(task.PriorityId);
                var listOfNotes = this.taskNotesService.GetAll(task.Id);
                task.NumberOfNotes = listOfNotes.Count();
            }

            return this.View(listWithTasks);
        }

        [Route("ToDoList/{listId:int}/Task/Details/{id:int}")]
        public async Task<IActionResult> Details(int id, int listId)
        {
            var task = new TaskDetailVM
            {
                ListId = listId,
                ToDoTask = await this.toDoTaskService.GetByIdAsync(id)
            };
            task.ToDoTask.Status = await this.statusService.GetByIdAsync(task.ToDoTask.StatusId);
            task.ToDoTask.Category = await this.categoryService.GetByIdAsync(task.ToDoTask.CategoryId);
            task.ToDoTask.Priority = await this.priorityService.GetByIdAsync(task.ToDoTask.PriorityId);
            task.ToDoTask.List = await this.toDoListService.GetByIdAsync(task.ToDoTask.ListId);

            return this.View(task);
        }

        [Route("ToDoList/{listId:int}/Tasks/Add")]
        [HttpGet]
        public IActionResult Add(int listId)
        {
            var categories = this.categoryService.GetAll();
            var priorities = this.priorityService.GetAll();
            var createTaskViewModel = new CreateTaskVM
            {
                ListId = listId
            };

            FillSetectedList.FillTaskSelectedLists(createTaskViewModel, categories, priorities, null);

            return this.View(createTaskViewModel);
        }

        [Route("ToDoList/{listId:int}/Tasks/Add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(int listId, CreateTaskVM task)
        {
            var parsePriority = int.TryParse(task.PrioritiesSelectedList.SelectedPriority, out var priorityId);
            var parseCategory = int.TryParse(task.CategoriesSelectedList.SelectedCategory, out var categoryId);

            if (!parsePriority || !parseCategory)
            {
                return this.RedirectToAction("Add", new { listId = task.ListId });
            }

            ToDoTaskDto toDoTask = task.ToDoTask;

            toDoTask.ListId = listId;
            toDoTask.PriorityId = priorityId;
            toDoTask.CategoryId = categoryId;
            toDoTask.StatusId = 1;

            toDoTask.List = null!;
            toDoTask.Priority = null!;
            toDoTask.Category = null!;
            toDoTask.Status = null!;

            toDoTask.CreationDate = DateTimeOffset.Now;

            var result = await this.validator.ValidateAsync(task.ToDoTask);

            if (!result.IsValid)
            {
                var categories = this.categoryService.GetAll();
                var priorities = this.priorityService.GetAll();

                FillSetectedList.FillTaskSelectedLists(task, categories, priorities, null);

                result.AddToModelState(this.ModelState);

                return this.View("Add", task);
            }

            var taskId = await this.toDoTaskService.AddAsync(task.ToDoTask);

            return this.RedirectToAction("Details", new { id = taskId, listId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id, int listId)
        {
            var createTaskViewModel = new CreateTaskVM();
            var categories = this.categoryService.GetAll();
            var priorities = this.priorityService.GetAll();
            var statuses = this.statusService.GetAll();

            FillSetectedList.FillTaskSelectedLists(createTaskViewModel, categories, priorities, statuses);

            createTaskViewModel.ToDoTask = await this.toDoTaskService.GetByIdAsync(id);
            createTaskViewModel.ListId = listId;
            createTaskViewModel.ToDoTask.Reminder = false;

            return this.View(createTaskViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CreateTaskVM task)
        {
            var parsePriority = int.TryParse(task.PrioritiesSelectedList.SelectedPriority, out var priorityId);
            var parseCategory = int.TryParse(task.CategoriesSelectedList.SelectedCategory, out var categoryId);
            var parseStatusy = int.TryParse(task.StatusesSelectedList.SelectedStatus, out var statusId);

            if (!parsePriority || !parseCategory || !parseStatusy)
            {
                return this.View("Edit", task);
            }

            ToDoTaskDto toDoTask = task.ToDoTask;

            toDoTask.ListId = task.ListId;
            toDoTask.PriorityId = priorityId;
            toDoTask.CategoryId = categoryId;
            toDoTask.StatusId = statusId;
            toDoTask.IsCompleted = this.statusService.GetByIdAsync(statusId).Result.Name == "Completed";

            toDoTask.List = null!;
            toDoTask.Priority = null!;
            toDoTask.Category = null!;
            toDoTask.Status = null!;

            var result = await this.validator.ValidateAsync(task.ToDoTask);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Edit", task);
            }

            var taskId = await this.toDoTaskService.UpdateAsync(task.ToDoTask.Id, task.ToDoTask);

            return this.RedirectToAction("Details", new { id = taskId, listId = task.ListId });
        }

        public async Task<IActionResult> Delete(int id, int listId)
        {
            await this.toDoTaskService.DeleteAsync(id);

            return this.RedirectToAction("Index", new { listId });
        }
    }
}

ToDoApplication.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using ToDoApplication.Domain.Models;
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject Reminder TaskReminder

@{
    var reminder = await TaskReminder.CheckIfRemindTask(@User.Identity?.Name);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApplication.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApplication.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand mr-10" asp-area="" asp-controller="Home" asp-action="Index">ToDoList KC</a>
                <partial name="_Reminder" model="reminder" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Index">Lists</a>
                            </li>
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TaskCategory" asp-action="Index">Task category</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TaskStatus" asp-action="Index">Task statuses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="TaskPriority" asp-action="Index">Task priorities</a>
                                </li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoList KC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApplication.Web/Views/Shared/_Reminder.cshtml
@model (bool, ReminderVM)

<style>
    #bell {
        color: cornflowerblue;
        animation: blink 5s infinite;
    }

    .modal-header {
        color: cornflowerblue;
    }
</style>

@if (Model.Item1)
{
    <i class="bi bi-bell-fill fa-10x mr-10" id="bell" data-bs-toggle="modal" data-bs-target="#myModal">
        <span class="position-absolute top-5 start-10 translate-middle p-1 bg-danger border border-light rounded-circle">
            <span class="visually-hidden">New alerts</span>
        </span>
    </i>

    <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Your reminder for tasks:</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    @for (int i = 0; i < Model.Item2.ListId.Count(); i++)
                    {
                        <text>· </text>
                        @Model.Item2.Name[i]
                        <text> - </text>
                        <a href="@Url.Action("Details", "ToDoTask", new { id = Model.Item2.TaskId[i], listId = Model.Item2.ListId[i] })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Go to task
                        </a>
                        <br />
                    }
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>
    <i>                                             </i>
}