ToDoApplication.Web/Controllers/TaskPriorityController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoApplication.Application.DTOs;
using ToDoApplication.Application.Interfaces;
using ToDoApplication.Domain.Models;

namespace ToDoApplication.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TaskPriorityController : Controller
    {
        private readonly ITaskPriorityService priorityService;
        private readonly IToDoTaskService taskService;
        private readonly IValidator<TaskPriorityDto> validator;

        public TaskPriorityController(
            ITaskPriorityService priorityService,
            IToDoTaskService taskService,
            IValidator<TaskPriorityDto> validator)
        {
            this.priorityService = priorityService;
            this.taskService = taskService;
            this.validator = validator;
        }

        public IActionResult Index()
        {
            var taskPriority = this.priorityService.GetAll();

            return this.View(taskPriority);
        }

        [Route("TaskPriority/Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            var taskPriority = await this.priorityService.GetByIdAsync(id);
            taskPriority.Tasks = this.taskService.GetAll().Where(x => x.StatusId == id);

            return this.View(taskPriority);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View(new TaskPriorityDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(TaskPriorityDto priority)
        {
            var result = await this.validator.ValidateAsync(priority);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Add", priority);
            }

            var priorityId = await this.priorityService.AddAsync(priority);

            return this.RedirectToAction("Details", new { id = priorityId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var taskPriority = await this.priorityService.GetByIdAsync(id);

            return this.View(taskPriority);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TaskPriorityDto priority)
        {
            var result = await this.validator.ValidateAsync(priority);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Edit", priority);
            }

            var priorityId = await this.priorityService.UpdateAsync(priority.Id, priority);

            return this.RedirectToAction("Details", new { id = priorityId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.priorityService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

ToDoApplication.Web/Views/TaskPriority/Add.cshtml
@model TaskPriorityDto

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Task priority</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApplication.Web/Views/TaskPriority/Details.cshtml
@model TaskPriorityDto;

@{
    ViewData["Title"] = "Details";
}

<table class="table table-sm table-bordered table-striped" aria-describedby="TaskCategoryDetails">
    <tbody>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Id)
            </th>
            <td>
                @Model.Id
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Name)
            </th>
            <td>
                @Model.Name
            </td>
        </tr>
        <tr>
            <th>Number of task using this priority:</th>
            <td>@Model.Tasks.Count()</td>
        </tr>
    </tbody>
</table>

@*<a class="btn btn-warning" asp-controller="Admin" asp-action="Edit" asp-route-productId="@Model?.ProductId">Edit</a>*@
<a class="btn btn-secondary" asp-controller="TaskPriority" asp-action="Index">Back</a>

ToDoApplication.Web/Views/TaskPriority/Edit.cshtml
@model TaskPriorityDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Task priority</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApplication.Web/Views/TaskPriority/Index.cshtml
@model IEnumerable<TaskPriorityDto>;

@{
    ViewData["Title"] = "Index";
    var i = 1;
}

<h1 style="text-align:center">Tasks priorities</h1>

<p>
    <a class="btn btn-primary btn-sm" asp-action="Add">Create New</a>
</p>

<div>
    <table class="table table-hover" aria-describedby="TaskCategory">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var priority in Model)
            {
                <tr>
                    <td>
                        @i
                    </td>
                    <td>
                        @Html.DisplayFor(c => priority.Name)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "TaskPriority", new { id = priority.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Edit
                        </a>
                        <a href="@Url.Action("Details", "TaskPriority", new { id = priority.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Details
                        </a>
                        <a onclick="return confirm('Do you want to delete this row?')" href="@Url.Action("Delete", "TaskPriority", new { id = priority.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Delete
                        </a>
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
</div>