ToDoApplication.Web/Controllers/TaskCategoryController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoApplication.Application.DTOs;
using ToDoApplication.Application.Interfaces;

namespace ToDoApplication.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TaskCategoryController : Controller
    {
        private readonly ITaskCategoryService taskCategoryService;
        private readonly IToDoTaskService taskService;
        private readonly IValidator<TaskCategoryDto> validator;

        public TaskCategoryController(
            ITaskCategoryService taskCategoryService,
            IToDoTaskService taskService,
            IValidator<TaskCategoryDto> validator)
        {
            this.taskCategoryService = taskCategoryService;
            this.taskService = taskService;
            this.validator = validator;
        }

        public IActionResult Index()
        {
            var taskCategories = this.taskCategoryService.GetAll();

            return this.View(taskCategories);
        }

        [Route("TaskCategory/Details/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            var taskCategory = await this.taskCategoryService.GetByIdAsync(id);
            taskCategory.Tasks = this.taskService.GetAll().Where(x => x.StatusId == id);

            return this.View(taskCategory);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View(new TaskCategoryDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(TaskCategoryDto category)
        {
            var result = await this.validator.ValidateAsync(category);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Add", category);
            }

            var categoryId = await this.taskCategoryService.AddAsync(category);

            return this.RedirectToAction("Details", new { id = categoryId });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var taskCategory = await this.taskCategoryService.GetByIdAsync(id);

            return this.View(taskCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TaskCategoryDto category)
        {
            var result = await this.validator.ValidateAsync(category);

            if (!result.IsValid)
            {
                result.AddToModelState(this.ModelState);

                return this.View("Edit", category);
            }

            var categoryId = await this.taskCategoryService.UpdateAsync(category.Id, category);

            return this.RedirectToAction("Details", new { id = categoryId });
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.taskCategoryService.DeleteAsync(id);

            return this.RedirectToAction("Index");
        }
    }
}

ToDoApplication.Web/Views/TaskCategory/Add.cshtml
@model TaskCategoryDto

@{
    ViewData["Title"] = "Add";
}

<h1>Add</h1>

<h4>Task categories</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApplication.Web/Views/TaskCategory/Details.cshtml
@model TaskCategoryDto;

@{
    ViewData["Title"] = "Details";
}

<table class="table table-sm table-bordered table-striped" aria-describedby="TaskCategoryDetails">
    <tbody>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Id)
            </th>
            <td>
                @Model.Id
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Name)
            </th>
            <td>
                @Model.Name
            </td>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Description)
            </th>
            <td>
                @Model.Description
            </td>
        </tr>
        <tr>
            <th>Number of task using this category:</th>
            <td>@Model.Tasks.Count()</td>
        </tr>
    </tbody>
</table>

@*<a class="btn btn-warning" asp-controller="Admin" asp-action="Edit" asp-route-productId="@Model?.ProductId">Edit</a>*@
<a class="btn btn-secondary" asp-controller="TaskCategory" asp-action="Index">Back</a>

ToDoApplication.Web/Views/TaskCategory/Edit.cshtml
@model TaskCategoryDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TaskCategoryDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ToDoApplication.Web/Views/TaskCategory/Index.cshtml
@model IEnumerable<TaskCategoryDto>;

@{
    ViewData["Title"] = "Index";
    var i = 1;
}

<h1 style="text-align:center">Tasks categories</h1>

<p>
    <a class="btn btn-primary btn-sm" asp-action="Add">Create New</a>
</p>

<div>
    <table class="table table-hover" aria-describedby="TaskCategory">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var category in Model)
            {
                <tr>
                    <td>
                        @i
                    </td>
                    <td>
                        @Html.DisplayFor(c => category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(c => category.Description)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "TaskCategory", new { id = category.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Edit
                        </a>
                        <a href="@Url.Action("Details", "TaskCategory", new { id = category.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Details
                        </a>
                        <a onclick="return confirm('Do you want to delete this row?')" href="@Url.Action("Delete", "TaskCategory", new { id = category.Id })" class="btn btn-primary btn-sm">
                            <i class="fa fa-mobile"></i> Delete
                        </a>
                    </td>
                </tr>
                i++;
            }
        </tbody>
    </table>
</div>